changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: ✨ Features
      labels:
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - fix
    - title: ⚡️ Performance Improvements
      labels:
        - perf
    - title: 🔧 Miscellaneous Tasks
      labels:
        - chore
    - title: ♻️ Refactor
      labels:
        - refactor
    - title: 📝 Documentation
      labels:
        - doc
    - title: 💄 Styling
      labels:
        - style
    - title: ✅ Testing
      labels:
        - test
    - title: 👷 CI
      labels:
        - ci
