name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features --- 特性"
    labels:
      - "feat"
      - "feature"
  - title: "🐛 Bug Fixes --- Bug 修复"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "📝 Documentation --- 文档"
    labels:
      - "doc"
      - "docs"
  - title: "⚡ Performance --- 性能优化"
    labels:
      - "perf"
  - title: "🚜 Refactor --- 代码重构"
    labels:
      - "refactor"
  - title: "🎨 Styling --- 样式"
    labels:
      - "style"
  - title: "🧪 Testing --- 测试"
    labels:
      - "test"
      - "tests"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## What’s Changed

  $CHANGES
