name: Generate Changelog

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Generate release-notes
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        env:
          OUTPUT: docs/release-notes.md
      - name: Commit
        run: |
          git checkout main
          git config user.name 'Luren'
          git config user.email '68656403+luren-dc@users.noreply.github.com'
          set +e docs/release-notes.md
          git add docs/release-notes.md
          git commit -m "chore(release-notes): Update release notes"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
