name: Release And Publish Python Package

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  generate-release-body:
    if: contains(github.event.head_commit.message, 'chore(release)')
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate release body
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          args: -vv --unreleased --strip all

  publish:
    runs-on: ubuntu-latest
    needs: [generate-release-body]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pdm install
      - name: Build and publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          pdm build
          pdm publish --username __token__ --password $PYPI_TOKEN

  release:
    runs-on: ubuntu-latest
    needs: [generate-release-body,publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
      - name: Get version
        run: |
          echo PACKAGE_VERSION=`pdm show --version` >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ needs.generate-release-body.outputs.release_body }}
          tag_name: v${{ env.PACKAGE_VERSION }}
